language: python

sudo: false

python:
  - '2.7'
  - '3.5'
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls
  - pip install pytest

script:
  - coverage run --source=pshtt pytest
  - flake8 .
