language: python

sudo: false

python:
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pytest-cov pytest coveralls
  - pip install -e .

script:
  - pytest --cov=pshtt
  - flake8 .

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jsf9k
  password:
    secure: j41EqJy+kcDqP/f6j9NbEg1r8oAH5Kpj7vstIpkdOoHSPN63iERAoAdgfoL9wb0Y6N4LPmnXhQEA2Ey0KsJXaK7kcRymURsJ7ZlK/843rXKz24+fIRt+UoLGqm59QYbDdkEoTx+2yKBlWX1qz7fC8hVficvRdIzWtq7QNs54XtdJUtiM2bsnIRclB3mrBZpJLnuw6dP4sPQQ4GglItRN6QcFJn/Xrhe17YouXvszM4hwSVdAYDS/V/nzMVEyDdAuTb1evZoWv56RdiZdiRGjkkFpZLG2TVzMYVE1mnDSTixYryRA5qRermJC+vwiI8HXlWqpwrg6m9y5XpU6tg7epOpvZHCTUT4K6Sn+tvpBnamqHqh4TQJJmpuGi+/Q4j/kIstie7oS6eQvcTg17AznDDA0trZKtg+Q4vUBqq5IgCCGvkLpuhwvgX7NcsFS90mdruc3YIdZktCl3Jzucsb9JMiIBp+ES2Q3DDWXk0Xt82ju/6uJ7pFlBO6W6sb+5se7tZV97k3jGbD3pYgy7VDL1VAm+HqmC3veS2E96MOBQQ5yeLGVng42iSH4xws5z0vAb+3IIZAYn+g2WCubGa8w9tltj6O1FJ5jYkQUCPsTG2yPa2NDWfbzWfwpOUqaX7t4pcbzvSp6WdVv3XvhkI4ZgxTjKD7YQ0fz9dksamxFJKk=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
